# Generated by Django 2.1.1 on 2018-09-25 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eze', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='thumb',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to=''),
        ),
    ]
